
#### pont tf entre gz et Ros2 #####
- ros_topic_name: "/tf"
  gz_topic_name: "/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS #  BIDIRECTIONAL or ROS_TO_GZ


#### capteur Imu
- ros_topic_name: "/drone/imu"
  gz_topic_name: "/drone/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS #  BIDIRECTIONAL or ROS_TO_GZ

##### Capteur gps####

- ros_topic_name: "/drone/gps"
  gz_topic_name: "/drone/gps"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS #  BIDIRECTIONAL or ROS_TO_GZ



#### topic plugin dynamique motor #####
- ros_topic_name: "/faucon_drone/command/motor_speed"
  gz_topic_name: "/faucon_drone/command/motor_speed"
  ros_type_name: "actuator_msgs/msg/Actuators"
  gz_type_name: "gz.msgs.Actuators"
  direction: ROS_TO_GZ

##### odometry #####

- ros_topic_name: "/faucon_drone/odom" 
  gz_topic_name: "/faucon_drone/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS #  BIDIRECTIONAL or ROS_TO_GZ


## Camera #####

- ros_topic_name: "/drone/camera/image_raw"
  gz_topic_name: "/drone/camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS # BIDIRECTIONAL or ROS_TO_GZ


# gz topic published by Sensors plugin (Camera)
- ros_topic_name: "/drone/camera/camera_info"
  gz_topic_name: "/drone/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS # BIDIRECTIONAL or ROS_TO_GZ




- ros_topic_name: "clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS  # BIDIRECTIONAL or ROS_TO_GZ


# gz topic published by JointState plugin
- ros_topic_name: "joint_states"
  gz_topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS