#!/bin/sh
#
# @name Faucon Gazebo x500 mono cam
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_mono_cam}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

# Faucon autonomous SITL defaults. These need to be applied before EKF2 and
# commander start, so keep them in the airframe file instead of only in .post.
param set NAV_DLL_ACT 0
param set COM_DLL_EXCEPT 4
param set COM_RC_IN_MODE 4
param set CBRK_SUPPLY_CHK 894281
param set COM_ARM_WO_GPS 2

param set SYS_HAS_BARO 0
param set EKF2_BARO_CTRL 0

param set EKF2_EV_CTRL 15
param set EKF2_HGT_REF 3
param set EKF2_MAG_TYPE 5
param set EKF2_GPS_CHECK 0
