row_length: 10
rows_count: 10
row_width: 0.85
ground_headland: 8.0
rows_curve_budget: 0.0
# row_segment_straight_length_min: 0.5
# row_segment_straight_length_max: 0.6
row_segments:
  - straight
# plant_spacing_min: 0.5
# plant_spacing_max: 0.6
hole_prob: 0.0
hole_size_max: 0
litters: 20
litter_types:
  - coke_can
  - retro_pepsi_can
weeds: 0
crop_types:
  - maize_02
